[package]
name = "test"
version = "0.1.0"
authors = ["Paul <pl59@st-andrews.ac.uk>"]
edition = "2018"

[dependencies]
sacn = { path = "../Lib"}
lazy_static = "1.4.0"

[[bin]]
name = "test"
path = "src/main.rs"
