language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose --no-default-features
  - cargo test --verbose --no-default-features
  - cargo build --verbose --no-default-features --features std
  - cargo test --verbose --no-default-features --features std
