language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose --all --no-default-features
  - cargo test --verbose --all --no-default-features
  - cargo build --verbose --all --no-default-features --features std
  - cargo test --verbose --all --no-default-features --features std
matrix:
  exclude:
  - rust: stable
    script: cargo build --verbose --all --no-default-features
  - rust: stable
    script: cargo test --verbose --all --no-default-features
  - rust: beta
    script: cargo build --verbose --all --no-default-features
  - rust: beta
    script: cargo test --verbose --all --no-default-features
