[package]
name = "mcast_simple"
version = "0.1.0"
authors = ["Lan2u <pl59@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.3.4", features = ["reuseport"] }
