[package]
name = "test_rcv"
version = "0.1.0"
authors = ["Paul <paul@lancasterzone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sacn = { path = "../Lib"}
lazy_static = "1.4.0"
